/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserDirectoryEntry {
    principal: Principal;
    profile?: UserProfile;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Listing {
    listedAt: bigint;
    price: bigint;
    listingDescription: string;
}
export interface LoginEvent {
    principal: Principal;
    loginAt: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Transaction {
    id: string;
    status: {
        __kind__: "cancelled";
        cancelled: string;
    } | {
        __kind__: "pending";
        pending: string;
    } | {
        __kind__: "completed";
        completed: {
            billOfSale: string;
        };
    };
    createdAt: bigint;
    seller: Principal;
    stripePaymentIntentId: string;
    buyer: Principal;
    siteId: string;
    price: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Site {
    id: string;
    status: {
        __kind__: "published";
        published: string;
    } | {
        __kind__: "sold";
        sold: {
            billOfSale: string;
            salePrice: bigint;
            buyer: Principal;
        };
    } | {
        __kind__: "draft";
        draft: null;
    } | {
        __kind__: "listed";
        listed: Listing;
    };
    title: string;
    content: string;
    owner: Principal;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Dashboard {
    listings: Array<Site>;
    sites: Array<Site>;
    transactions: Array<Transaction>;
}
export interface ChatMessage {
    id: string;
    tradeProposalStatus?: Variant_pending_accepted_declined;
    content: string;
    sender: Principal;
    timestamp: bigint;
    tradeProposalSiteId?: string;
    receiver: Principal;
    tradeProposalSiteTitle?: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    bio: string;
    username: string;
    displayName: string;
    joinedAt: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_accepted_declined {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPendingTransaction(siteId: string, paymentIntentId: string): Promise<string>;
    createProfile(username: string, displayName: string, bio: string): Promise<void>;
    createSite(title: string, description: string, content: string): Promise<string>;
    finalizeTransaction(transactionId: string, billOfSale: string): Promise<void>;
    getAllUsers(): Promise<Array<UserDirectoryEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLoginEvents(): Promise<Array<LoginEvent>>;
    getMarketplaceListingIds(): Promise<Array<string>>;
    getMarketplaceListings(): Promise<Array<Site>>;
    getMessages(partner: Principal): Promise<Array<ChatMessage>>;
    getProfile(user: Principal): Promise<UserProfile>;
    getSiteById(siteId: string): Promise<Site>;
    getSiteByTitle(title: string): Promise<Site>;
    getSitesByOwner(owner: Principal): Promise<Array<Site>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTransactionById(id: string): Promise<Transaction>;
    getUserDashboard(): Promise<Dashboard>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isSiteListed(siteId: string): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listSite(id: string, price: bigint, listingDescription: string): Promise<void>;
    proposeTrade(to: Principal, siteId: string): Promise<string>;
    publishSite(siteId: string): Promise<string>;
    recordLogin(): Promise<void>;
    respondToTradeProposal(messageId: string, accept: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(to: Principal, content: string): Promise<string>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unlistSite(siteId: string): Promise<void>;
    updateBio(bio: string): Promise<void>;
    updateDisplayName(displayName: string): Promise<void>;
    updateSite(id: string, title: string, description: string, content: string): Promise<void>;
    updateUsername(username: string): Promise<void>;
}
import type { ChatMessage as _ChatMessage, Dashboard as _Dashboard, Listing as _Listing, Site as _Site, StripeSessionStatus as _StripeSessionStatus, Transaction as _Transaction, UserDirectoryEntry as _UserDirectoryEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPendingTransaction(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPendingTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPendingTransaction(arg0, arg1);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async createSite(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSite(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSite(arg0, arg1, arg2);
            return result;
        }
    }
    async finalizeTransaction(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeTransaction(arg0, arg1);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserDirectoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoginEvents(): Promise<Array<LoginEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoginEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoginEvents();
            return result;
        }
    }
    async getMarketplaceListingIds(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceListingIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceListingIds();
            return result;
        }
    }
    async getMarketplaceListings(): Promise<Array<Site>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceListings();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceListings();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return result;
        }
    }
    async getSiteById(arg0: string): Promise<Site> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteById(arg0);
                return from_candid_Site_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteById(arg0);
            return from_candid_Site_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteByTitle(arg0: string): Promise<Site> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteByTitle(arg0);
                return from_candid_Site_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteByTitle(arg0);
            return from_candid_Site_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSitesByOwner(arg0: Principal): Promise<Array<Site>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSitesByOwner(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSitesByOwner(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionById(arg0: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionById(arg0);
                return from_candid_Transaction_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionById(arg0);
            return from_candid_Transaction_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserDashboard(): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDashboard();
                return from_candid_Dashboard_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDashboard();
            return from_candid_Dashboard_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSiteListed(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSiteListed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSiteListed(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listSite(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.listSite(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSite(arg0, arg1, arg2);
            return result;
        }
    }
    async proposeTrade(arg0: Principal, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.proposeTrade(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.proposeTrade(arg0, arg1);
            return result;
        }
    }
    async publishSite(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.publishSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishSite(arg0);
            return result;
        }
    }
    async recordLogin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLogin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLogin();
            return result;
        }
    }
    async respondToTradeProposal(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToTradeProposal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToTradeProposal(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unlistSite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlistSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlistSite(arg0);
            return result;
        }
    }
    async updateBio(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBio(arg0);
            return result;
        }
    }
    async updateDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayName(arg0);
            return result;
        }
    }
    async updateSite(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSite(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSite(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsername(arg0);
            return result;
        }
    }
}
function from_candid_ChatMessage_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Site_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Site): Site {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserDirectoryEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDirectoryEntry): UserDirectoryEntry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        pending: null;
    } | {
        accepted: null;
    } | {
        declined: null;
    }]): Variant_pending_accepted_declined | null {
    return value.length === 0 ? null : from_candid_variant_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        published: string;
    } | {
        sold: {
            billOfSale: string;
            salePrice: bigint;
            buyer: Principal;
        };
    } | {
        draft: null;
    } | {
        listed: _Listing;
    };
    title: string;
    content: string;
    owner: Principal;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
}): {
    id: string;
    status: {
        __kind__: "published";
        published: string;
    } | {
        __kind__: "sold";
        sold: {
            billOfSale: string;
            salePrice: bigint;
            buyer: Principal;
        };
    } | {
        __kind__: "draft";
        draft: null;
    } | {
        __kind__: "listed";
        listed: Listing;
    };
    title: string;
    content: string;
    owner: Principal;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        owner: value.owner,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tradeProposalStatus: [] | [{
            pending: null;
        } | {
            accepted: null;
        } | {
            declined: null;
        }];
    content: string;
    sender: Principal;
    timestamp: bigint;
    tradeProposalSiteId: [] | [string];
    receiver: Principal;
    tradeProposalSiteTitle: [] | [string];
}): {
    id: string;
    tradeProposalStatus?: Variant_pending_accepted_declined;
    content: string;
    sender: Principal;
    timestamp: bigint;
    tradeProposalSiteId?: string;
    receiver: Principal;
    tradeProposalSiteTitle?: string;
} {
    return {
        id: value.id,
        tradeProposalStatus: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.tradeProposalStatus)),
        content: value.content,
        sender: value.sender,
        timestamp: value.timestamp,
        tradeProposalSiteId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.tradeProposalSiteId)),
        receiver: value.receiver,
        tradeProposalSiteTitle: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.tradeProposalSiteTitle))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        cancelled: string;
    } | {
        pending: string;
    } | {
        completed: {
            billOfSale: string;
        };
    };
    createdAt: bigint;
    seller: Principal;
    stripePaymentIntentId: string;
    buyer: Principal;
    siteId: string;
    price: bigint;
}): {
    id: string;
    status: {
        __kind__: "cancelled";
        cancelled: string;
    } | {
        __kind__: "pending";
        pending: string;
    } | {
        __kind__: "completed";
        completed: {
            billOfSale: string;
        };
    };
    createdAt: bigint;
    seller: Principal;
    stripePaymentIntentId: string;
    buyer: Principal;
    siteId: string;
    price: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        seller: value.seller,
        stripePaymentIntentId: value.stripePaymentIntentId,
        buyer: value.buyer,
        siteId: value.siteId,
        price: value.price
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listings: Array<_Site>;
    sites: Array<_Site>;
    transactions: Array<_Transaction>;
}): {
    listings: Array<Site>;
    sites: Array<Site>;
    transactions: Array<Transaction>;
} {
    return {
        listings: from_candid_vec_n9(_uploadFile, _downloadFile, value.listings),
        sites: from_candid_vec_n9(_uploadFile, _downloadFile, value.sites),
        transactions: from_candid_vec_n27(_uploadFile, _downloadFile, value.transactions)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    profile: [] | [_UserProfile];
}): {
    principal: Principal;
    profile?: UserProfile;
} {
    return {
        principal: value.principal,
        profile: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: string;
} | {
    sold: {
        billOfSale: string;
        salePrice: bigint;
        buyer: Principal;
    };
} | {
    draft: null;
} | {
    listed: _Listing;
}): {
    __kind__: "published";
    published: string;
} | {
    __kind__: "sold";
    sold: {
        billOfSale: string;
        salePrice: bigint;
        buyer: Principal;
    };
} | {
    __kind__: "draft";
    draft: null;
} | {
    __kind__: "listed";
    listed: Listing;
} {
    return "published" in value ? {
        __kind__: "published",
        published: value.published
    } : "sold" in value ? {
        __kind__: "sold",
        sold: value.sold
    } : "draft" in value ? {
        __kind__: "draft",
        draft: value.draft
    } : "listed" in value ? {
        __kind__: "listed",
        listed: value.listed
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): Variant_pending_accepted_declined {
    return "pending" in value ? Variant_pending_accepted_declined.pending : "accepted" in value ? Variant_pending_accepted_declined.accepted : "declined" in value ? Variant_pending_accepted_declined.declined : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n21(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: string;
} | {
    pending: string;
} | {
    completed: {
        billOfSale: string;
    };
}): {
    __kind__: "cancelled";
    cancelled: string;
} | {
    __kind__: "pending";
    pending: string;
} | {
    __kind__: "completed";
    completed: {
        billOfSale: string;
    };
} {
    return "cancelled" in value ? {
        __kind__: "cancelled",
        cancelled: value.cancelled
    } : "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserDirectoryEntry>): Array<UserDirectoryEntry> {
    return value.map((x)=>from_candid_UserDirectoryEntry_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Site>): Array<Site> {
    return value.map((x)=>from_candid_Site_n10(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
