/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Dashboard {
  'listings' : Array<Site>,
  'sites' : Array<Site>,
  'transactions' : Array<Transaction>,
}
export interface Listing {
  'listedAt' : bigint,
  'price' : bigint,
  'listingDescription' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Site {
  'id' : string,
  'status' : { 'published' : string } |
    {
      'sold' : {
        'billOfSale' : string,
        'salePrice' : bigint,
        'buyer' : Principal,
      }
    } |
    { 'draft' : null } |
    { 'listed' : Listing },
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Transaction {
  'id' : string,
  'status' : { 'cancelled' : string } |
    { 'pending' : string } |
    { 'completed' : { 'billOfSale' : string } },
  'createdAt' : bigint,
  'seller' : Principal,
  'stripePaymentIntentId' : string,
  'buyer' : Principal,
  'siteId' : string,
  'price' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'joinedAt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPendingTransaction' : ActorMethod<[string, string], string>,
  'createProfile' : ActorMethod<[string, string, string], undefined>,
  'createSite' : ActorMethod<[string, string, string], string>,
  'finalizeTransaction' : ActorMethod<[string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarketplaceListingIds' : ActorMethod<[], Array<string>>,
  'getMarketplaceListings' : ActorMethod<[], Array<Site>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getSiteById' : ActorMethod<[string], Site>,
  'getSiteByTitle' : ActorMethod<[string], Site>,
  'getSitesByOwner' : ActorMethod<[Principal], Array<Site>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactionById' : ActorMethod<[string], Transaction>,
  'getUserDashboard' : ActorMethod<[], Dashboard>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSiteListed' : ActorMethod<[string], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listSite' : ActorMethod<[string, bigint, string], undefined>,
  'publishSite' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlistSite' : ActorMethod<[string], undefined>,
  'updateBio' : ActorMethod<[string], undefined>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateSite' : ActorMethod<[string, string, string, string], undefined>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];