/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'joinedAt' : IDL.Int,
});
export const UserDirectoryEntry = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : IDL.Opt(UserProfile),
});
export const LoginEvent = IDL.Record({
  'principal' : IDL.Principal,
  'loginAt' : IDL.Int,
});
export const Listing = IDL.Record({
  'listedAt' : IDL.Int,
  'price' : IDL.Nat,
  'listingDescription' : IDL.Text,
});
export const Site = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'published' : IDL.Text,
    'sold' : IDL.Record({
      'billOfSale' : IDL.Text,
      'salePrice' : IDL.Nat,
      'buyer' : IDL.Principal,
    }),
    'draft' : IDL.Null,
    'listed' : Listing,
  }),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'tradeProposalStatus' : IDL.Opt(
    IDL.Variant({
      'pending' : IDL.Null,
      'accepted' : IDL.Null,
      'declined' : IDL.Null,
    })
  ),
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'tradeProposalSiteId' : IDL.Opt(IDL.Text),
  'receiver' : IDL.Principal,
  'tradeProposalSiteTitle' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Text,
    'pending' : IDL.Text,
    'completed' : IDL.Record({ 'billOfSale' : IDL.Text }),
  }),
  'createdAt' : IDL.Int,
  'seller' : IDL.Principal,
  'stripePaymentIntentId' : IDL.Text,
  'buyer' : IDL.Principal,
  'siteId' : IDL.Text,
  'price' : IDL.Nat,
});
export const Dashboard = IDL.Record({
  'listings' : IDL.Vec(Site),
  'sites' : IDL.Vec(Site),
  'transactions' : IDL.Vec(Transaction),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPendingTransaction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createSite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'finalizeTransaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserDirectoryEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoginEvents' : IDL.Func([], [IDL.Vec(LoginEvent)], ['query']),
  'getMarketplaceListingIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMarketplaceListings' : IDL.Func([], [IDL.Vec(Site)], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(ChatMessage)], []),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getSiteById' : IDL.Func([IDL.Text], [Site], ['query']),
  'getSiteByTitle' : IDL.Func([IDL.Text], [Site], ['query']),
  'getSitesByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Site)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransactionById' : IDL.Func([IDL.Text], [Transaction], ['query']),
  'getUserDashboard' : IDL.Func([], [Dashboard], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSiteListed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listSite' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'proposeTrade' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'publishSite' : IDL.Func([IDL.Text], [IDL.Text], []),
  'recordLogin' : IDL.Func([], [], []),
  'respondToTradeProposal' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlistSite' : IDL.Func([IDL.Text], [], []),
  'updateBio' : IDL.Func([IDL.Text], [], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateSite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'joinedAt' : IDL.Int,
  });
  const UserDirectoryEntry = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : IDL.Opt(UserProfile),
  });
  const LoginEvent = IDL.Record({
    'principal' : IDL.Principal,
    'loginAt' : IDL.Int,
  });
  const Listing = IDL.Record({
    'listedAt' : IDL.Int,
    'price' : IDL.Nat,
    'listingDescription' : IDL.Text,
  });
  const Site = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'published' : IDL.Text,
      'sold' : IDL.Record({
        'billOfSale' : IDL.Text,
        'salePrice' : IDL.Nat,
        'buyer' : IDL.Principal,
      }),
      'draft' : IDL.Null,
      'listed' : Listing,
    }),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'tradeProposalStatus' : IDL.Opt(
      IDL.Variant({
        'pending' : IDL.Null,
        'accepted' : IDL.Null,
        'declined' : IDL.Null,
      })
    ),
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'tradeProposalSiteId' : IDL.Opt(IDL.Text),
    'receiver' : IDL.Principal,
    'tradeProposalSiteTitle' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Text,
      'pending' : IDL.Text,
      'completed' : IDL.Record({ 'billOfSale' : IDL.Text }),
    }),
    'createdAt' : IDL.Int,
    'seller' : IDL.Principal,
    'stripePaymentIntentId' : IDL.Text,
    'buyer' : IDL.Principal,
    'siteId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Dashboard = IDL.Record({
    'listings' : IDL.Vec(Site),
    'sites' : IDL.Vec(Site),
    'transactions' : IDL.Vec(Transaction),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPendingTransaction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createSite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'finalizeTransaction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserDirectoryEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoginEvents' : IDL.Func([], [IDL.Vec(LoginEvent)], ['query']),
    'getMarketplaceListingIds' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMarketplaceListings' : IDL.Func([], [IDL.Vec(Site)], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(ChatMessage)], []),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getSiteById' : IDL.Func([IDL.Text], [Site], ['query']),
    'getSiteByTitle' : IDL.Func([IDL.Text], [Site], ['query']),
    'getSitesByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Site)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransactionById' : IDL.Func([IDL.Text], [Transaction], ['query']),
    'getUserDashboard' : IDL.Func([], [Dashboard], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSiteListed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listSite' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'proposeTrade' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'publishSite' : IDL.Func([IDL.Text], [IDL.Text], []),
    'recordLogin' : IDL.Func([], [], []),
    'respondToTradeProposal' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlistSite' : IDL.Func([IDL.Text], [], []),
    'updateBio' : IDL.Func([IDL.Text], [], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateSite' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };